-- Insert programs with Arabic and English content
INSERT INTO programs (
    id, type, title_ar, title_en, description_ar, description_en, 
    cover_image_url, host_ar, host_en, category_id, status, featured,
    episode_count, duration_avg, launch_date, latest_episode_date, slug
) VALUES 
(
    gen_random_uuid(), 
    'video', 
    'ترانزيت', 
    'Transit',
    'برنامج وثائقي يتتبع قصص الأشخاص في رحلات انتقالهم وهجرتهم، ويستكشف التحديات والفرص التي يواجهونها في بحثهم عن حياة أفضل',
    'A documentary program that follows people''s stories in their journeys of migration and transition, exploring the challenges and opportunities they face in their search for a better life',
    '/covers/transit.jpg',
    'ليلى الوثائقية',
    'Layla Documentary',
    (SELECT id FROM categories WHERE slug = 'culture' LIMIT 1),
    'active',
    true,
    24,
    45,
    '2024-02-01',
    '2025-01-12',
    'transit'
),
(
    gen_random_uuid(), 
    'video', 
    'شمال جنوب', 
    'North South',
    'برنامج حواري يجمع بين ضيوف من الشمال والجنوب العالمي لمناقشة القضايا المشتركة والاختلافات الثقافية والاقتصادية',
    'A talk show that brings together guests from the Global North and South to discuss common issues and cultural and economic differences',
    '/covers/north-south.jpg',
    'د. أحمد الدولي',
    'Dr. Ahmed International',
    (SELECT id FROM categories WHERE slug = 'politics' LIMIT 1),
    'active',
    false,
    18,
    52,
    '2024-04-15',
    '2025-01-08',
    'north-south'
),
(
    gen_random_uuid(), 
    'audio', 
    'حدث ومعنى', 
    'Event and Meaning',
    'برنامج صوتي تحليلي يتناول الأحداث الجارية ويضعها في سياقها التاريخي والثقافي والسياسي لفهم معناها الأعمق',
    'An analytical audio program that addresses current events and places them in their historical, cultural and political context to understand their deeper meaning',
    '/covers/event-meaning.jpg',
    'د. محمد المحلل',
    'Dr. Mohammed Analyst',
    (SELECT id FROM categories WHERE slug = 'politics' LIMIT 1),
    'active',
    true,
    56,
    35,
    '2024-01-10',
    '2025-01-14',
    'event-and-meaning'
),
(
    gen_random_uuid(), 
    'audio', 
    'أصل الخبر', 
    'Source of News',
    'برنامج استقصائي يتعمق في الأحداث الجارية ويكشف الخلفيات والسياقات التي تقف وراء الأخبار الرئيسية',
    'An investigative program that delves into current events and reveals the backgrounds and contexts behind major news',
    '/covers/source-news.jpg',
    'أحمد الصحفي',
    'Ahmed Journalist',
    (SELECT id FROM categories WHERE slug = 'politics' LIMIT 1),
    'active',
    true,
    45,
    35,
    '2024-01-15',
    '2025-01-10',
    'source-of-news'
),
(
    gen_random_uuid(), 
    'video', 
    'ترانزستور', 
    'Transistor',
    'برنامج تقني يستكشف أحدث التطورات في عالم التكنولوجيا وتأثيرها على حياتنا اليومية والمستقبل',
    'A technical program that explores the latest developments in the world of technology and their impact on our daily lives and the future',
    '/covers/transistor.jpg',
    'سارة التقنية',
    'Sara Tech',
    (SELECT id FROM categories WHERE slug = 'technology' LIMIT 1),
    'active',
    false,
    32,
    28,
    '2024-03-20',
    '2025-01-08',
    'transistor'
),
(
    gen_random_uuid(), 
    'mixed', 
    'جيوبوليتيكا', 
    'Geopolitica',
    'تحليل عميق للأحداث السياسية العالمية من خلال فهم الجغرافيا السياسية وتأثيرها على القرارات الاستراتيجية',
    'Deep analysis of global political events through understanding political geography and its impact on strategic decisions',
    '/covers/geopolitica.jpg',
    'د. محمد الجغرافي',
    'Dr. Mohammed Geographer',
    (SELECT id FROM categories WHERE slug = 'politics' LIMIT 1),
    'active',
    true,
    28,
    42,
    '2024-02-10',
    '2025-01-12',
    'geopolitica'
),
(
    gen_random_uuid(), 
    'audio', 
    'لخصنا لك', 
    'We Summarized for You',
    'ملخص يومي سريع لأهم الأحداث والتطورات في المنطقة والعالم، مقدم بأسلوب مبسط وواضح',
    'A quick daily summary of the most important events and developments in the region and the world, presented in a simple and clear style',
    '/covers/summary.jpg',
    'فريق التحرير',
    'Editorial Team',
    (SELECT id FROM categories WHERE slug = 'politics' LIMIT 1),
    'active',
    false,
    120,
    8,
    '2024-01-01',
    '2025-01-15',
    'we-summarized'
)
ON CONFLICT (slug) DO UPDATE SET
    title_ar = EXCLUDED.title_ar,
    title_en = EXCLUDED.title_en,
    description_ar = EXCLUDED.description_ar,
    description_en = EXCLUDED.description_en,
    cover_image_url = EXCLUDED.cover_image_url,
    host_ar = EXCLUDED.host_ar,
    host_en = EXCLUDED.host_en,
    category_id = EXCLUDED.category_id,
    status = EXCLUDED.status,
    featured = EXCLUDED.featured,
    episode_count = EXCLUDED.episode_count,
    duration_avg = EXCLUDED.duration_avg,
    launch_date = EXCLUDED.launch_date,
    latest_episode_date = EXCLUDED.latest_episode_date,
    updated_at = NOW();
